version: '3.8'

services:
  paye-calculator:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - WATCHPACK_POLLING=${WATCHPACK_POLLING:-false}
    stdin_open: true
    tty: true